urls.py
from django.urls import path

from . import views

app_name = "physics"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:page_name>", views.load_static_page, name="static_page")
]

models.py
from django.db import models

# Create your models here.

views.py
from django.shortcuts import render
from django.core.paginator import Paginator

def index(request):
    return render(request, "physics/index.html")

def load_static_page(request, page_name):
    lessons = ["gravity", "newtons-law", "drag-and-friction", "conservation", "buoyancy"]
    data = {}
    if page_name in lessons:
        page_index = lessons.index(page_name)
        data = {
            "lessons": lessons, 
            "page_index": page_index + 1,
        }    

        # If there is a next page then add it to data
        if page_index + 1 != len(lessons):
            data.update({"next": lessons[page_index + 1]})

        # If there is a previous page then add it to data
        if page_index != 0:
            data.update({"prev": lessons[page_index - 1]})

    return render(request, f"physics/{page_name}.html", data)

def get_posts_data(lesson):
    lessons = ["gravity", "newtons-law", "drag-and-friction", "conservation", "buoyancy"]
    p = Paginator(lessons, 1)
    page_number = lessons.index(lesson)     # Get the page number
    page = p.page(page_number)              # Get the page object
    page_posts = page.object_list

    posts_user_ratings_dict = {post: get_rating_value(post, request.user) for post in page_posts}

    return {
        "posts_user_ratings_dict": posts_user_ratings_dict,
        "page_obj": page
    }

templates/physics/about.html
{% extends "physics/layout.html" %}

{% block title %}
    About this project
{% endblock %}

{% block body %}

<h3>About this project</h3>

<p>
    This is my final project for Harvard's Introduction to 
    Computer Science course, CS50.
</p>

<p>
    In my previous experience programming (GCSE's, A levels and a small amount in my 
    Maths degree), I mostly used Python with a little bit of Java, R, Matlab and HTML. 
    Since CS50's last two weeks of lectures before the final project were on web design, 
    I decided it would be a good idea to make a website for my final project in order 
    to best develop and cement the skills that I have learnt in the course.
</p>

<p>
    My original vision for this project was somewhat larger than what
    you see here. The plan was to create lessons for lots of different things that 
    occur in space and then relate these back to the laws of nature that govern them. 
    The interesting part for me is to then create interactive learning environments 
    using JavaScript that would help a learner understand aspects of a law of nature.
</p>

<p>
    I quickly realised that I needed to limit the number of topics and scripts that I 
    was going to write. I decided to give lessons on just enough laws of nature to be 
    able to understand the motion of objects moving in a vaccuum in space, in order 
    for a student to understand what was going on in my asteroids game. 
</p>

<p>
    To make the lessons more interesting, I made the ball simulator with the idea 
    that is could be relatively easily repurposed for each of the lessons.
</p>

<p>
    Lastly, I was not sure what I wanted to have as a landing page. After testing a couple
    of ideas, namely a simple static background with text over the top and a bootstrap 
    carousel of pictures from the NASA website, I had the idea of having a moving background 
    that used Javascript and chose to do exactly that.
</p>

<p>
    Contact: joe.ovenden17@gmail.com
    <br><a href="https://github.com/JoeOvenden?tab=repositories" style="color: black">My GitHub</a>
</p>


{% endblock %}

templates/physics/buoyancy.html
{% extends "physics/layout.html" %}

{% block title %}
    Buoyancy
{% endblock %}

{% block body %}

<!-- Beginning of conservation of energy lesson text-->
<h3>Buoyancy</h3>

<p>Buoyancy, also known as upthrust, is an upward force exerted by a fluid upon a partially of fully submerged object and is the force that is responsible for objects floating. The magntitude of this force is equal to the mass of fluid that the object is displacing multiplied by the acceleration due to gravity.</p>

<p>Suppose there was a sphere of radius, r and density, d, which is fully submerged in a fluid of density D, in a gravitational field of strength, g. The force due to buoyancy will be:

<p class="centered padded"><i>mass of fluid displaced * acceleration due to gravity =</i></p>

<p class="centered padded"><i>volume of fluid displaced * fluid density * acceleration due to gravity =</i></p>

<p class="centered padded"><i>volume of the sphere * fluid density * acceleration due to gravity =</i></p>

<p class="centered padded"><i><sup>4</sup>&frasl;<sub>3</sub>&pi;r<sup>3</sup>Dg</i></p>





<p>The force due to gravity will be:</p>

<p class="centered padded"><i>mass * -acceleration due to gravity =</i></p>

<p class="centered padded"><i>volume of sphere * sphere density * -acceleration due to gravity =</i></p>

<p class="centered padded"><i>-<sup>4</sup>&frasl;<sub>3</sub>&pi;r<sup>3</sup>dg</i></p>



<p>At this point hopefully you will notice that the two equations look very similar. Let's see what we get if we now try to resolve the two forces.</p>
	
<p class="centered padded"><i>Resultant force = </i></p>

<p class="centered padded"><i><sup>4</sup>&frasl;<sub>3</sub>&pi;r<sup>3</sup>Dg - <sup>4</sup>&frasl;<sub>3</sub>&pi;r<sup>3</sup>dg = </i></p>

<p class="centered padded"><i>(4</sup>&frasl;<sub>3</sub>&pi;r<sup>3</sup>g)(D - d)</i></p>	

<p>Looking at the left hand bracket we see that g, r^3, pi and 4/3 are all positive, meaning the left hand bracket is a positive number. Looking at the right hand bracket we see that it is positive when D > d, it is 0 when D = d and it is negative when D < d. A positive resultant force means the sphere will be accelerated upwards, a negative resultant force means the sphere will be accelerated downwards, and force of 0 means there will be no acceleration.</p>

<p>The result of this is that an object will float to the top in a fluid when it's density is lower than the fluid density, it will sink when it's density is higher than the fluid density, and it won't move when it's density is equal to the fluid density.</p>

<!-- Ball simulator canvas-->
<canvas id="simulator-canvas"></canvas>

<!-- Ball simulator options -->
<table>
  <tr>
    <th>Fluid density (kgm<sup>-3</sup>):</th>
    <th><input type="text" value="1.23" id="fluid-density-text"></th>
    <th><input type="range" min="0" max="1000" value="1.23" class="slider" id="fluid-density-slider"></th>
    <th>&nbsp; Fluid:</th>
    <th>
        <select name= "fluid" id="fluid-density-selecter">
            <option value="empty"></option>
            <option selected value="emptySpace">Vacuum</option>
            <option selected value="earth">Air</option>
            <option value="water">Water</option>
        </select>
    </th>
  </tr>
  <tr>
    <th>Ball material density (kgm<sup>-3</sup>): </th>
    <th><input type="text" value="7850" id="material-density-text"></th>
    <th><input type="range" min="35" max="20000" value="7850" class="slider" id="material-density-slider"></th>
    <th>&nbsp; Material: </th>
    <th>
      <select name= "material" id="material-density-selecter">
          <option value="empty"></option>
          <option value="cork">Cork</option>
          <option value="woodYew">Wood (Yew)</option>
          <option value="ice">Ice</option>
          <option value="water">Water</option>
          <option value="concrete">Concrete</option>
          <option value="titanium">Titanium</option>
          <option value="steel">Steel</option>
          <option selected value="iron">Iron</option>
          <option value="gold">Gold</option>
      </select>
    </th>
  </tr>
</table>
<table>
  <tr>
      <th class="th-number-padded">Bounce on ceiling: <input type="checkbox" id="ceiling-bounce"></th>
  </tr>
</table>

{% load static %}
<script src="{% static 'physics/scripts/simulator.js' %}"></script>

<h3 style="padding-top: 10%;"><a href="/simulator">Go to full simulator</a></h3>
<p>You are ready for the full simulator (with many more settings), check it out!</p>

{% include 'physics/lesson-pagination.html' %}

{% endblock %}

templates/physics/conservation.html
{% extends "physics/layout.html" %}

{% block title %}
    Conservation Laws
{% endblock %}

{% block body %}

<!-- Beginning of conservation of energy lesson text-->
<h3>Conservation of Energy</h3>
<p>
  Energy comes in various different forms, for example; we can have energy in the 
  form of movement, called kinetic energy; energy in the form of heat; potential 
  energy, energy that is "stored" in an object by gravity or some other means 
  (imagine a book on a shelf, if we push the book off the shelf, it will gain 
  kinetic energy. We say that the potential energy is converted to kinetic energy).
</p>

<p>The law of conservation of energy is that:</p>

<p class="centered padded">
  Energy is always conserved, meaning it is never destroyed. Energy can only 
  ever be converted from one form to another.
</p>

<p>
  So for instance say we take some wood and burn it. There is chemical energy 
  stored in the wood, when we burn it we convert that energy mostly into heat 
  energy, but some into light too. That heat energy will then spread out and heat 
  up the air and all the surroundings. 
</p>

<p>
  Another example: we drop a heavy ball onto the ground. The ball starts off 
  with gravitational potential energy which gets converted into kinetic energy. 
  Then when the ball hits the ground, it sends vibrations through the ground 
  which is also kinetic energy. Instead of having a ball that is moving fast, 
  instead we now have a ball that is still and the ground that is vibrating ever so 
  slightly more than it was before.
</p>

<p>
  Here is the simulator again with fluid density but now you have another option that 
  determines how much energy is lost when the ball collides with a wall.
</p>

<p>Questions to think about: </p>

<ul>
  <li>
    <p><strong>
      When the ball slows down, where does that kinetic energy go?
    </p></strong>
  </li>
  <li>
    <p><strong>
      What happens when the ball is in a vaccuum (fluid density is 0) 
      and no energy is lost when the ball bounces?
    </p></strong>
  </li>
</ul>

<!-- Ball simulator canvas -->
<canvas id="simulator-canvas"></canvas>

<!-- Ball simulator options-->
<table>
  <tr>
    <th>Fluid density (kgm<sup>-3</sup>):</th>
    <th><input type="text" value="1.23" id="fluid-density-text"></th>
    <th><input type="range" min="0" max="1000" value="1.23" class="slider" id="fluid-density-slider"></th>
    <th>&nbsp; Fluid:</th>
    <th>
        <select name= "fluid" id="fluid-density-selecter">
            <option value="empty"></option>
            <option selected value="air">Air</option>
            <option value="water">Water</option>
        </select>
    </th>
  </tr>

  <tr>
    <th>Coefficient of friction: </th>
    <th><input type="text" value=0.1 id="friction-text"></th>
    <th><input type="range" min=0 max=1.5 value=0.1 step=0.01 class="slider" id="friction-slider"></th>
</tr>

  <tr>
    <th>Energy lost on bounce (%): </th>
    <th><input type="text" value="50" id="energy-lost-text"></th>
    <th><input type="range" min="0" max="100" value="50" class="slider" id="energy-lost-slider"></th>
  </tr>

  <tr>
    <th>Bounce on ceiling: <input type="checkbox" id="ceiling-bounce"></th>
  </tr>
</table>

{% load static %}
<script src="{% static 'physics/scripts/simulator.js' %}"></script>

<!-- End of ball simulator -->

<!-- Gif of a newtons cradle -->
<h5 class="centered" style="padding-top: 5%;">
  A newton's cradle demonstrating conservation of energy.
</h5>
<img src="/static/images/newtons_cradle.gif" alt="newtons cradle" class="centered-image">

<!-- Beginning of conservation of momentum lesson text -->
<h3 style="padding-top: 8%;">Conservation of Momentum</h3>

<p>
  The momentum of an object is defined as such:
</p>

<p class="centered padded">Momentum = mass x velocity</p>

<p>
  Now it turns out momentum is also conserved, meaning it can never be lost, 
  it can only be transferred to and from different objects.
</p>

<p>
  Let's look at an example:
</p>
<p>
  Imagine a rocket in space not moving. It currently has net momentum of 0 in all directions.
  Say the pilot now wants to move the rocket in a direction s. Well conservation of 
  momentum has to be conserved and so what happens is that for the rocket to gain velocity
  , gas is shot out in the direction opposite to s very fast.
</p>
<p>
  The gas that is shot out has negative momentum in the direction s, since it is travelling
  in the opposite direction and so through conservation of momentum, the rocket gains
  positive momentum in th direction s of the same magnitude as that of the gas. 
</p>
<p>
  The result is that the net momentum is still 0, but instead we now have gas travelling
  in one direction and the rocket travelling in the other.
</p>

{% include 'physics/lesson-pagination.html' %}

{% endblock %}

templates/physics/drag-and-friction.html
{% extends "physics/layout.html" %}

{% block title %}
    Drag and Friction
{% endblock %}

{% block body %}

<!-- Beginning of drag lesson text -->
<h3>Drag</h3>

<p>
  While not fundamental laws of nature, drag and friction are constently in 
  effect in life on Earth. Drag is the force of resistance against movement 
  from a fluid, such as air or water, when something is moving through it. 
  So for example if someone throws a ball through the air, the ball is constantly 
  having to push air particles out of the way, which slows the ball down. 
  This, together with gravity, is the reason that when we throw a ball, it 
  doesn't just keep going out the same speed in a straight line. 
  It is being acted upon by drag and gravity and so these forces are 
  changing the ball's path.
</p>

<p>
  We can see how big an effect drag has when looking at the fastest 
  speeds by vehicles set on Earth vs. in space:
</p>

<ul>
  <li>
    The fastest speed ever recorded by a vehicle on earth was by the x-15 rocketship in 1967 going at a speed of 7,232 Km/hr.
  </li>
  <li>
    The fastest spacecraft Helios 2 however set a record in 1976 of a whopping 252,792 Km/hr. 
  </li>
</ul>
  
<p>Why such a big difference?</p>

<p>
  The largest factor is drag. On earth an areoplane is constantly being 
  slowed down by the air. It's always bumping into air particles that take energy 
  away from the plane, so the plane has to always be burning fuel to stay at the 
  same speed. In fact, all aircraft will reach a speed where the acceleration from 
  the engine is the same as the decceleration from the drag and so it can go no 
  faster. 
  On the other hand a rocket travelling through space is in a vacuum, 
  meaning there is no air to slow the rocket down. 
  If the rocket keeps accelerating it will just get faster and faster.
</p>

<!-- Beginning of friction lesson text -->
<h3 style="padding-top: 10%;">Friction</h3>

<p>
  Friction is a similar to drag in that it is a force of resistance against movement, 
  but it is between solids. An example would be if you press your thumb hard against 
  the table and then try to move it to the side, you'll notice that at first, when you 
  put just a small amount of force in, your thumb won't move. You have to put more force 
  in to move it. This is because friction is resisting the movement, and so you must 
  put in enough force to overcome the friction. 
</p>

<p>
  Now the magnitude of the friction is down to the surfaces that are coming into contact. 
  For instance ice produces very little friction where as concrete would produce much 
  more. We could observe this by rolling a tennis ball gently along some ice or concrete. 
  With the same initial force, the tennis ball will go much further on the ice because 
  there is much less energy being taken out by the ice.
</p>

<p>
  Now what do we mean when we say energy being "taken out of" the ice? Where does it go? 
  Is it destroyed?
</p>

<p>Well this conveniently brings us onto our final topic...
  But first, time for you to have a play around with drag and friction. See what happens in the simulator 
  below when you change fluid density or the friction coefficient.
  You may notice that in the simulator the coefficient is called the coefficient of rolling friction.
  This is because an object that is rolling will experience less friction than one that is just sliding
  along the surface, and so we have a different coefficient for a rolling object.
</p>
<p>Questions to think about: </p>

<ul>
  <li>
    <p><strong>
      What happens to the movement of the ball when it is in water rather than air?
    </p></strong>
  </li>
  <li>
    <p><strong>
      What happens when the ball is in a vaccuum? (Meaning the fluid density is 0).
    </p></strong>
  </li>
</ul>

<!-- Ball simulator canvas-->
<canvas id="simulator-canvas"></canvas>

<!-- Ball simulator options -->
<table>
  <tr>
    <th>Fluid density (kgm<sup>-3</sup>):</th>
    <th><input type="text" value="1.23" id="fluid-density-text"></th>
    <th><input type="range" min="0" max="1000" value="1.23" class="slider" id="fluid-density-slider"></th>
    <th>&nbsp; Fluid:</th>
    <th>
        <select name= "fluid" id="fluid-density-selecter">
            <option value="empty"></option>
            <option selected value="emptySpace">Vacuum</option>
            <option selected value="earth">Air</option>
            <option value="water">Water</option>
        </select>
    </th>
    <tr>
      <th>Coefficient of friction: </th>
      <th><input type="text" value=0.1 id="friction-text"></th>
      <th><input type="range" min=0 max=1.5 value=0.1 step=0.01 class="slider" id="friction-slider"></th>
  </tr>
  </tr>

  <tr>
    <th>Bounce on ceiling: <input type="checkbox" id="ceiling-bounce"></th>
  </tr>
</table>

{% load static %}
<script src="{% static 'physics/scripts/simulator.js' %}"></script>

{% include 'physics/lesson-pagination.html' %}

{% endblock %}

templates/physics/gravity.html
{% extends "physics/layout.html" %}

{% block title %}
    Gravity
{% endblock %}

{% block body %}

<!-- Laws of nature overview text-->
<h3>Understanding the laws of motion</h3>

<p>
    There are many laws that govern our world. Often when we talk about
    laws we are referring to man-made laws, constructed and enforced by governments 
    to control  certain aspects of a society. However unlike man-made laws, 
    there are laws that are not socially constructed. 
    They "existed" before us and will be here after we're gone, and what's more, 
    they can't be broken! These are the laws of nature.
</p>
<p>
    Now there are many laws of nature to be explored, understood and utilised, 
    however here we will conscern ourselves with the basics and specifically ones 
    that are important for the understanding of space, namely, the laws of motion.
</p>

<!-- Beginning of gravity lesson text -->
<h3>Gravity</h3>

<p>
    Gravity is the law of attraction of mass. That is, that everything with mass 
    is attracting everything else with mass. The more mass, the stronger the 
    attraction. That is why we as humans in the presence of the Earth's gravity 
    are pulled towards the Earth, and if we were to say, throw a ball up into the 
    air, it will come down. What is less familiar to us however is the situation of 
    not being in the presence of a strong gravitation field, like for instance, in 
    most of space. We'll come back to gravity in the section on black holes but 
    for now, this brings us to another law of nature.
</p>
<p>
    But first, have a play around with the simulator below. Change the strength 
    of gravity, g, and see what affect this has when you throw the ball.
</p>

<!-- Ball simulator canvas-->
<canvas id="simulator-canvas"></canvas>

<!-- Ball simulator options -->
<table>
    <tr>
        <th>Strength of gravity, g (ms<sup>-2</sup>):</th>
        <th><input type="text" value="9.81" id="g-text"></th>
        <th><input type="range" min="0" max="30" value="9.81" class="slider" id="g-slider"></th>
        <th>&nbsp; Planet:</th>
        <th>
            <select name= "gravity" id="g-selector">
                <option value="empty"></option>
                <option value="emptySpace">Vacuum</option>
                <option value="moon">The Moon</option>
                <option value="mercury">Mercury</option>
                <option value="venus">Venus</option>
                <option selected value="earth">Earth</option>
                <option value="saturn">Saturn</option>
                <option value="neptune">Neptune</option>
                <option value="jupiter">Jupiter</option>
            </select>
        </th>
    </tr>
    <tr>
        <th>Bounce on ceiling: <input type="checkbox" id="ceiling-bounce"></th>
    </tr>
</table>

{% load static %}
<script src="{% static 'physics/scripts/simulator.js' %}"></script>

{% include 'physics/lesson-pagination.html' %}

{% endblock %}

templates/physics/index.html
{% extends "physics/layout.html" %}

{% block title %}
    The laws of motion
{% endblock %}

{% block body %}

<!-- Background canvas and script -->
<canvas id="canvas"></canvas>
{% load static %}
<script src="{% static 'physics/scripts/blackhole.js' %}" type="module"></script>

{% endblock %}

templates/physics/layout.html
      {% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'physics/images/favicon.ico' %}">
        <link href="{% static 'physics/styles.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
        {% block head %}{% endblock %}
    </head>

        <body>

            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
                <a class="navbar-brand" href="{% url 'physics:index' %}">A Short Guide to the Laws of Motion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Lessons
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'physics:static_page' 'gravity' %}">Gravity</a>
                        <a class="dropdown-item" href="{% url 'physics:static_page' 'newtons-law' %}">Newton's First Law</a>
                        <a class="dropdown-item" href="{% url 'physics:static_page' 'drag-and-friction' %}">Drag and Friction</a>
                        <a class="dropdown-item" href="{% url 'physics:static_page' 'conservation' %}">Conservation of Energy and Momentum</a>
                        <a class="dropdown-item" href="{% url 'physics:static_page' 'buoyancy' %}">Buoyancy</a>
                      </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'physics:static_page' 'simulator' %}">Simulator</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'physics:static_page' 'about' %}">About this project</a></li>
                    <li class="nav-item"><a class="nav-link" href="https://github.com/JoeOvenden/CS50-Final-Project">Source code</a></li>
                  </ul>
                </div>
              </nav>
            <!-- End of navbar -->

            {% block body %}{% endblock %}



            <!-- scripts required for bootstrap navbar -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </body>



</html>

templates/physics/lesson-pagination.html
<!-- Pagination linking to other lessons -->
<nav aria-label="laws-of-nature-pagination" id="bottom-padination">
  <ul class="pagination">

    <!-- Display "previous" in paginator -->
    {% if prev %}
        <li class="page-item"> 
          <a class="page-link" href="{% url 'physics:static_page' prev %}">Previous</a>
        </li>
    {% endif %}


    <!-- Display all the lessons as numbers -->
    {% for lesson in lessons %}
      <li class="page-item{% if page_index == forloop.counter %} active{% endif %}"><a class="page-link" href="{% url 'physics:static_page' lesson %}">{{ forloop.counter }}</a></li>
    {% endfor %}
    

    <!-- Display "next" in paginator -->
    {% if next %}
      <li class="page-item">
        <a class="page-link" href="{% url 'physics:static_page' next %}">Next</a>
      </li>
    {% endif %}

  </ul>
</nav>

templates/physics/newtons-law.html
{% extends "physics/layout.html" %}

{% block title %}
    Newton's First Law
{% endblock %}

{% block body %}

<!-- Beginning of newtons first law lesson text -->
<h3>Newton's First Law of Motion</h3>

<p><strong>Newton's first law of motion</strong> is as follows:</p>

<p class="centered padded">
    A body remains at rest, or in motion at a constant speed in a 
    straight line, unless acted upon by a force.
</p>

<p>
    Or in other words, if nothing happens to an object (no force is applied to it), 
    then it will maintain it's velocity. Now this law we might find a little more 
    surprising. Indeed, generally for life on earth, if we want to go somewhere we 
    have to continually put it effort. Whether it's effort from our body to walk 
    or run, or fuel in the engine of a car being burnt, the action is continuous. 
    We can't just move a little bit and expect for that energy to keep us moving.
</p>

<p>
    Perhaps this is why the famous Greek philosopher Aristotle came up with his 
    own law (which turned out to be false), that an object's natural state is to 
    be at rest and if you stop trying to move it, it will come back to rest. 
    This would be a more familiar framework, but is in fact, overlooking a 
    great deal of things that happen in all of our interactions on Earth.
</p>

<p>
  This brings us on to the concept of Drag and Friction.
</p>

{% include 'physics/lesson-pagination.html' %}

{% endblock %}